package ReservationSystem;
import java.awt.Color;
import java.awt.Font;

public class registration_form extends javax.swing.JFrame {

    /**
     * Creates new form reservation_form
     */
    public registration_form() {
        initComponents();
            passCON.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            PassCONKeyReleased(evt);
        }
    });
             passSTR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
            PassSTRKeyReleased(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        PassSTR = new javax.swing.JLabel();
        PassCON = new javax.swing.JLabel();
        userEmail = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        passSTR = new javax.swing.JPasswordField();
        passCON = new javax.swing.JPasswordField();
        label1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");
        setBackground(new java.awt.Color(0, 204, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 675));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("SimSun-ExtB", 2, 48)); // NOI18N
        jLabel5.setText("Asher's Diner");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 350, 70));

        PassSTR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PassSTRKeyReleased(evt);
            }
        });
        getContentPane().add(PassSTR, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 200, 24));

        PassCON.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PassCONKeyReleased(evt);
            }
        });
        getContentPane().add(PassCON, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 200, 24));

        userEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userEmail.setBorder(null);
        userEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailActionPerformed(evt);
            }
        });
        userEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userEmailKeyReleased(evt);
            }
        });
        getContentPane().add(userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 385, 394, 45));

        userName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userName.setBorder(null);
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 394, 45));
        userName.getAccessibleContext().setAccessibleDescription("");

        btn_register.setBackground(new java.awt.Color(0, 102, 102));
        btn_register.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 150, 50));

        btn_clear.setBackground(new java.awt.Color(0, 102, 102));
        btn_clear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 140, 50));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 150, 50));

        passSTR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passSTR.setToolTipText("");
        passSTR.setBorder(null);
        passSTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passSTRActionPerformed(evt);
            }
        });
        getContentPane().add(passSTR, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 394, 45));

        passCON.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passCON.setBorder(null);
        passCON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passCONActionPerformed(evt);
            }
        });
        getContentPane().add(passCON, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 385, 394, 45));
        passCON.getAccessibleContext().setAccessibleDescription("");

        label1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 204, 204));
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 501, 745, 30));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EXIT");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 90, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/regBG.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 675));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        userEmail.setText(null);
        userName.setText(null);
        passCON.setText(null);
        passSTR.setText(null);
        label1.setText(null);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
     
    }//GEN-LAST:event_btn_registerActionPerformed

    private void PassSTRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassSTRKeyReleased
    String password = new String(passCON.getPassword());
    int passwordLength = password.length();
    String strength;
    Color color;

    if (passwordLength >= 12) {
        strength = "Strong";
        color =new Color(0, 100, 0); 
    } else if (passwordLength >= 8) {
        strength = "Good";
        color = Color.yellow; 
    } else {
        strength = "Weak";
        color = Color.RED; 
    }
    PassSTR.setText("Password Strength: " + strength);
    PassSTR.setForeground(color);
    
    }//GEN-LAST:event_PassSTRKeyReleased

    private void userEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userEmailKeyReleased
 String name = userEmail.getText();
    StringBuilder capitalized = new StringBuilder();
    boolean capitalizeNext = true;
    for (char c : name.toCharArray()) {
        if (Character.isWhitespace(c)) {
            capitalizeNext = true;
            capitalized.append(c);
        } else if (capitalizeNext) {
            capitalized.append(Character.toUpperCase(c));
            capitalizeNext = false;
        } else {
            capitalized.append(Character.toLowerCase(c));
        }
    }
        userEmail.setText(capitalized.toString());
    }//GEN-LAST:event_userEmailKeyReleased

    private void userEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void passSTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passSTRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passSTRActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PassCONKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassCONKeyReleased
    String password1 = new String(passCON.getPassword());
    String password2 = new String(passSTR.getPassword());

    if (password1.equals(password2)) {
        PassCON.setText("Passwords Match");
        PassCON.setForeground(Color.GREEN);
    } else {
        PassCON.setText("Passwords Do Not Match");
        PassCON.setForeground(Color.RED);
    }
    }//GEN-LAST:event_PassCONKeyReleased

    private void passCONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passCONActionPerformed

    }//GEN-LAST:event_passCONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PassCON;
    private javax.swing.JLabel PassSTR;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label1;
    private javax.swing.JPasswordField passCON;
    private javax.swing.JPasswordField passSTR;
    private javax.swing.JTextField userEmail;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
